# Generated by Django 3.2.25 on 2024-03-20 22:28

import AuthenticationSystem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationSystem', '0004_alter_userprofile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to=AuthenticationSystem.models.user_profile_pic_path),
        ),
    ]
