# Generated by Django 5.0.1 on 2024-03-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeCapsuleManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='seal_capsule',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='capsulecontent',
            name='file',
            field=models.FileField(max_length=500, upload_to='static/capsule_content/%Y/%m/%d/'),
        ),
    ]
