# Generated by Django 5.0.1 on 2024-03-17 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeCapsuleManagement', '0002_capsule_seal_capsule_alter_capsulecontent_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capsule',
            old_name='seal_capsule',
            new_name='status',
        ),
    ]
