# Generated by Django 5.0.1 on 2024-03-21 01:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeCapsuleManagement', '0005_rename_capsule_status_capsule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
